version: '3'
services:
  postgres:
    image: postgres:14.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Wishma22
    ports:
      - "5432:5432"
volumes:
  postgres-data:
