server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/arcade
    username: postgres
    password: Wishma22
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true