spring:
  datasource:
    url: jdbc:postgresql://arcade-db-1.cqcamnunylzc.us-east-2.rds.amazonaws.com/arcade
    username: postgres
    password: Wishma22
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/
#    password: Wishma22
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true