spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    password: Wishma22
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true