server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://34.138.247.58/arcade
    username: postgres
    password: Wishma22!
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true